### ISSUE TITLE
Remove gesture handler typings

### ISSUE THREAD

**Issue by ddzirt** [igor90007/Translater#3]
1. There is no reason to have Types folder in root(unless really needed). Should be inside app or src folder -> typings folder
2. There is no reason to have React Native Gesture Handler typings in project(here they are: https://github.com/kmagiera/react-native-gesture-handler/blob/master/react-native-gesture-handler.d.ts)

**Comment by igor90007** [comment]
1. It will be changed in a next merge request.
2. I'm not sure about this. Cause I had tried to remove React Native Gesture Handler typing and app crashed.
