### ISSUE TITLE
Use Typescript way of typing for components

### ISSUE THREAD

**Issue by ddzirt** [igor90007/Translater#4]
1. Here is the first one:
https://github.com/igor90007/translater/blob/37af9aa0032976c3379d5adcbbf5cb3537af960d/src/components/Text/DefaultText.tsx#L12

Should be like this:
``` javascript
const DefaultText: React.FC<Params> = ({ text, additionalStyles }) => (
```

Replace with proper typing for styling, use proper naming and set fields as not required(since they should not be as one):
```javascript
import { StyleProp, TextStyle } from 'react-native'

interface ITextProps {
  text?: string
  additionalStyles?: StyleProp<TextStyle>
}
```
**This is used to create a better code readability.**

Also this should be extending React Native text, not just setting styling and that is it, since this limits text component.

For reference(before you actually implement this), I will provide this(also do not forget to export your custom typing for your component):

```javascript
import { Text } from 'react-native'

export interface ITextProps extends Text {
```

This will allow you to inherit everything there is inside Text as a base and extend with what you actually need for this component or any other there is.

**Comment by igor90007** [comment]
ok

**Comment by ddzirt** [comment]
This is how your default text is meant to be used:

<img width="709" alt="Screen Shot 2019-05-05 at 12 05 11" src="https://user-images.githubusercontent.com/973562/57191418-0f74c380-6f2e-11e9-962d-7904b8508284.png">

And this is what happens right now:
<img width="775" alt="Screen Shot 2019-05-05 at 12 06 13" src="https://user-images.githubusercontent.com/973562/57191429-37fcbd80-6f2e-11e9-9bfe-6cae1051f9a5.png">
